// 主进程入口
import { app, BrowserWindow, Menu, Tray, ipcMain, nativeImage, shell, dialog, screen } from 'electron'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import fs from 'node:fs'
import {
  getDb, closeDb,
  listWorkRecords, createWorkRecord, updateWorkRecord, deleteWorkRecord, dailySummary,
  listReports, createReport, updateReport, deleteReport,
  listTemplates, createTemplate, updateTemplate, deleteTemplate,
  listScreenshots,
  timeline, heatmap, appUsage,
  exportAll, importAll, clearAll
} from './db'
import { getSettings, updateSettings, type AppSettings } from './settings'
import { testConnection, generateReport, generateTemplate, type GenerateReportInput } from './ai'
import { startScreenshot, stopScreenshot, isScreenshotRunning, captureNow } from './screenshot'
import { startAppTracker, stopAppTracker } from './appTracker'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

app.setName('牙牙乐日报助手')

const gotLock = app.requestSingleInstanceLock()
if (!gotLock) app.quit()

let mainWindow: BrowserWindow | null = null
let tray: Tray | null = null

function cryptoRandom(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {
    const r = Math.random() * 16 | 0
    return (c === 'x' ? r : (r & 0x3 | 0x8)).toString(16)
  })
}

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1280,
    height: 820,
    minWidth: 960,
    minHeight: 640,
    show: false,
    title: '牙牙乐日报助手',
    backgroundColor: '#ffffff',
    autoHideMenuBar: true,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false
    }
  })

  // 完全隐藏菜单栏
  Menu.setApplicationMenu(null)

  if (process.env.VITE_DEV_SERVER_URL) {
    mainWindow.loadURL(process.env.VITE_DEV_SERVER_URL)
    mainWindow.webContents.openDevTools()
  } else {
    mainWindow.loadFile(path.join(__dirname, '../dist/index.html'))
  }

  mainWindow.on('close', (e) => {
    if ((app as any).isQuitting) return
    e.preventDefault()
    mainWindow?.hide()
  })

  mainWindow.once('ready-to-show', () => mainWindow?.show())
}

function createTray() {
  const iconPath = path.join(__dirname, '../dist/icon.png')
  let trayIcon: Electron.NativeImage
  if (fs.existsSync(iconPath)) trayIcon = nativeImage.createFromPath(iconPath)
  else trayIcon = nativeImage.createEmpty()
  tray = new Tray(trayIcon)
  tray.setToolTip('牙牙乐日报助手')
  const menu = Menu.buildFromTemplate([
    { label: '打开主窗口', click: () => { mainWindow?.show(); mainWindow?.focus() } },
    { label: '退出', click: () => { (app as any).isQuitting = true; app.quit() } }
  ])
  tray.setContextMenu(menu)
  tray.on('click', () => { mainWindow?.show(); mainWindow?.focus() })
}

// ==================== 定时日报生成 ====================

let scheduledReportTimer: NodeJS.Timeout | null = null
let lastAutoReportDate: string | null = null

function startScheduledReport() {
  if (scheduledReportTimer) return
  scheduledReportTimer = setInterval(checkScheduledReport, 60000)
  console.log('[scheduled] 定时日报已启动, 时间:', getSettings().scheduledReportTime)
}

function stopScheduledReport() {
  if (scheduledReportTimer) {
    clearInterval(scheduledReportTimer)
    scheduledReportTimer = null
  }
}

function checkScheduledReport() {
  const settings = getSettings()
  if (!settings.scheduledReportEnabled || !settings.apiKey) return

  const now = new Date()
  const todayStr = now.toISOString().slice(0, 10)
  const currentTime = `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`

  if (currentTime !== settings.scheduledReportTime) return
  if (lastAutoReportDate === todayStr) return

  lastAutoReportDate = todayStr
  autoGenerateDailyReport()
}

async function autoGenerateDailyReport() {
  const settings = getSettings()
  if (!settings.apiKey) return

  const now = new Date()
  const todayStr = now.toISOString().slice(0, 10)

  const records = listWorkRecords({ startDate: todayStr, endDate: todayStr })
  if (records.length === 0) {
    console.log('[scheduled] 今日无工作记录, 跳过自动生成')
    return
  }

  console.log(`[scheduled] 开始自动生成日报, ${records.length} 条工作记录`)
  const reportId = cryptoRandom()
  createReport({
    id: reportId,
    title: '生成中...',
    type: 'daily',
    startDate: todayStr,
    endDate: todayStr,
    model: settings.model
  })

  const input: GenerateReportInput = {
    type: 'daily',
    startDate: todayStr,
    endDate: todayStr,
    records: records.map(r => ({ startedAt: r.startedAt, summary: r.summary, category: r.category ?? undefined })),
    customInstruction: settings.customInstruction,
    memoryContent: settings.memoryContent
  }

  generateReport(
    input,
    (chunk) => emit('report:stream-chunk', { id: reportId, chunk }),
    (full) => {
      const titleMatch = full.match(/^#\s+(.+)$/m)
      const title = titleMatch ? titleMatch[1].trim() : `日报 ${todayStr}`
      updateReport(reportId, { content: full, title, status: 'completed' })
      emit('report:status-changed', { id: reportId, status: 'completed', title, content: full })
      console.log('[scheduled] 日报自动生成完成:', title)
    },
    (err) => {
      updateReport(reportId, { status: 'failed', content: err.message })
      emit('report:status-changed', { id: reportId, status: 'failed', error: err.message })
      console.error('[scheduled] 日报自动生成失败:', err.message)
    }
  )
}

app.whenReady().then(() => {
  getDb()
  createWindow()
  createTray()
  startScreenshot()
  startAppTracker()
  startScheduledReport()
  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
    else mainWindow?.show()
  })
})

app.on('before-quit', () => {
  stopScreenshot()
  stopAppTracker()
  stopScheduledReport()
  closeDb()
})

// ==================== IPC ====================
function emit(channel: string, ...args: unknown[]) {
  const win = BrowserWindow.getAllWindows()[0]
  if (win && !win.isDestroyed()) win.webContents.send(channel, ...args)
}

ipcMain.on('window-minimize', () => mainWindow?.minimize())
ipcMain.on('window-maximize', () => {
  if (mainWindow?.isMaximized()) mainWindow.unmaximize()
  else mainWindow?.maximize()
})
ipcMain.on('window-close', () => mainWindow?.close())

ipcMain.handle('settings:get', () => getSettings())
ipcMain.handle('settings:update', (_e, patch: Partial<AppSettings>) => {
  return updateSettings(patch)
})

ipcMain.handle('ai:test-connection', () => testConnection())

ipcMain.handle('ai:generate-report', async (_e, input: GenerateReportInput) => {
  const reportId = cryptoRandom()
  createReport({
    id: reportId,
    title: '生成中...',
    type: input.type,
    startDate: input.startDate,
    endDate: input.endDate,
    model: getSettings().model
  })
  generateReport(
    input,
    (chunk) => emit('report:stream-chunk', { id: reportId, chunk }),
    (full) => {
      const titleMatch = full.match(/^#\s+(.+)$/m)
      const title = titleMatch ? titleMatch[1].trim() : `${input.type === 'daily' ? '日报' : input.type === 'weekly' ? '周报' : '月报'} ${input.startDate}`
      updateReport(reportId, { content: full, title, status: 'completed' })
      emit('report:status-changed', { id: reportId, status: 'completed', title, content: full })
    },
    (err) => {
      updateReport(reportId, { status: 'failed', content: err.message })
      emit('report:status-changed', { id: reportId, status: 'failed', error: err.message })
    }
  )
  return { id: reportId }
})

ipcMain.handle('ai:generate-template', async (_e, input: { reference: string; requirements: string; type: 'daily' | 'weekly' | 'monthly' }) => {
  generateTemplate(
    input.reference, input.requirements, input.type,
    (chunk) => emit('ai:template-stream-chunk', { chunk }),
    (full) => emit('ai:template-status-changed', { status: 'completed', content: full }),
    (err) => emit('ai:template-status-changed', { status: 'failed', error: err.message })
  )
  return { started: true }
})

// 工作记录
ipcMain.handle('work-records:list', (_e, input: { date?: string; startDate?: string; endDate?: string; limit?: number; offset?: number }) => {
  return listWorkRecords(input)
})
ipcMain.handle('work-records:create', (_e, input: { startedAt: string; summary: string; category?: string; endedAt?: string }) => {
  return createWorkRecord(input)
})
ipcMain.handle('work-records:update', (_e, input: { id: string; summary?: string; category?: string; startedAt?: string; endedAt?: string }) => {
  return updateWorkRecord(input)
})
ipcMain.handle('work-records:delete', (_e, input: { id: string }) => {
  deleteWorkRecord(input.id)
  return { ok: true }
})
ipcMain.handle('work-records:daily-summary', (_e, input: { date: string }) => {
  return dailySummary(input.date)
})

// 时间线/热力图/应用使用
ipcMain.handle('timeline:list', (_e, input: { startDate?: string; endDate?: string }) => timeline(input))
ipcMain.handle('heatmap:list', (_e, input: { startDate?: string; endDate?: string }) => heatmap(input))
ipcMain.handle('app-usage:list', (_e, input: { startDate?: string; endDate?: string }) => appUsage(input))

// 系统：显示器列表
ipcMain.handle('system:displays', () => {
  return screen.getAllDisplays().map((d, i) => ({
    id: i + 1,
    label: d.label || `显示器 ${i + 1}`,
    x: d.bounds.x,
    y: d.bounds.y,
    width: d.bounds.width,
    height: d.bounds.height,
    scaleFactor: d.scaleFactor,
    isPrimary: screen.getPrimaryDisplay().id === d.id
  }))
})

// 报告
ipcMain.handle('reports:list', (_e, input: { limit?: number; offset?: number }) => listReports(input))
ipcMain.handle('reports:delete', (_e, input: { id: string }) => { deleteReport(input.id); return { ok: true } })
ipcMain.handle('reports:update-title', (_e, input: { id: string; title: string }) => {
  updateReport(input.id, { title: input.title })
  return { ok: true }
})
ipcMain.handle('reports:update-content', (_e, input: { id: string; content: string }) => {
  updateReport(input.id, { content: input.content })
  return { ok: true }
})
ipcMain.handle('report:export-to-file', async (_e, input: { id: string; format: 'md' | 'txt' }) => {
  const reports = listReports({ limit: 1000 })
  const report = reports.find(r => r.id === input.id)
  if (!report) throw new Error('报告不存在')
  const ext = input.format === 'md' ? 'md' : 'txt'
  const res = await dialog.showSaveDialog({
    title: '导出报告',
    defaultPath: `${report.title}.${ext}`,
    filters: [{ name: input.format === 'md' ? 'Markdown' : '文本', extensions: [ext] }]
  })
  if (res.canceled || !res.filePath) return { ok: false, message: '已取消' }
  fs.writeFileSync(res.filePath, report.content, 'utf-8')
  return { ok: true, path: res.filePath }
})

// 模板
ipcMain.handle('report-templates:list', (_e, input: { type?: string }) => listTemplates(input?.type))
ipcMain.handle('report-templates:create', (_e, input: { name: string; type: string; content: string }) => createTemplate(input))
ipcMain.handle('report-templates:update', (_e, input: { id: string; name?: string; content?: string }) => updateTemplate(input))
ipcMain.handle('report-templates:delete', (_e, input: { id: string }) => { deleteTemplate(input.id); return { ok: true } })

// 截图
ipcMain.handle('screenshots:status', () => ({ running: isScreenshotRunning() }))
ipcMain.handle('screenshots:capture-now', async () => captureNow())

// 读取本地图片为 dataUrl（截图查看用）
ipcMain.handle('read-local-image', async (_e, filePath: string) => {
  try {
    const fs = await import('node:fs')
    if (!fs.existsSync(filePath)) return { ok: false, error: '文件不存在' }
    const buffer = fs.readFileSync(filePath)
    const ext = filePath.toLowerCase().endsWith('.png') ? 'png' : 'jpeg'
    return { ok: true, dataUrl: `data:image/${ext};base64,${buffer.toString('base64')}` }
  } catch (e: any) {
    return { ok: false, error: e?.message ?? '读取失败' }
  }
})
ipcMain.handle('screenshots:start', () => ({ ok: startScreenshot() }))
ipcMain.handle('screenshots:stop', () => { stopScreenshot(); return { ok: true } })
ipcMain.handle('screenshots:list', (_e, input: { date?: string; limit?: number }) => listScreenshots(input))

// 数据管理
ipcMain.handle('data-management:export', async () => {
  const res = await dialog.showSaveDialog({
    title: '导出数据备份',
    defaultPath: `daily-assistant-backup-${new Date().toISOString().slice(0, 10)}.json`,
    filters: [{ name: 'JSON 备份', extensions: ['json'] }]
  })
  if (res.canceled || !res.filePath) return { ok: false, message: '已取消' }
  fs.writeFileSync(res.filePath, JSON.stringify(exportAll(), null, 2), 'utf-8')
  return { ok: true, path: res.filePath }
})

ipcMain.handle('data-management:import', async () => {
  const res = await dialog.showOpenDialog({
    title: '导入数据备份',
    filters: [{ name: 'JSON 备份', extensions: ['json'] }],
    properties: ['openFile']
  })
  if (res.canceled || res.filePaths.length === 0) return { ok: false, message: '已取消' }
  const raw = fs.readFileSync(res.filePaths[0], 'utf-8')
  const data = JSON.parse(raw)
  if (!data.version) throw new Error('无效的备份文件')
  importAll(data)
  return { ok: true, message: '导入成功' }
})

ipcMain.handle('data-management:clear', () => { clearAll(); return { ok: true } })

// 文件
ipcMain.handle('file:read-as-base64', (_e, filePath: string) => {
  if (!fs.existsSync(filePath)) throw new Error('文件不存在')
  return fs.readFileSync(filePath).toString('base64')
})

ipcMain.handle('app:open-external', (_e, url: string) => { shell.openExternal(url); return { ok: true } })
ipcMain.handle('app:get-version', () => app.getVersion())
