directories:
  output: release_v2_1_6
  buildResources: build
appId: com.daily-assistant
productName: 牙牙乐日报助手
afterPack: build/afterPack.cjs
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
win:
  target: nsis
  icon: build/icon.ico
  signAndEditExecutable: false
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  installerIcon: build/icon.ico
  uninstallerIcon: build/icon.ico
  installerHeaderIcon: build/icon.ico
electronVersion: 28.3.3
